services:
  sync:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/yikakia/nga_grep:latest
    restart: unless-stopped
    command:
      - sync
      - --db=/data/nga.db
      - --loop-max=4m50s
      - --loop-min=30s
      - --th-lf=1.3
    environment:
      - OTEL_SERVICE_NAME=sync
    env_file:
      - .env
    volumes:
      - type: bind
        source: ${NGA_DATA_DIR?Please set NGA_DATA_DIR to a host directory that contains nga.db}
        target: /data

  api:
    image: ghcr.io/yikakia/nga_grep:latest
    restart: unless-stopped
    command:
      - api-server
      - --db=/data/nga.db
      - --cors=localhost,dashidai.yikakia.com,nga-grep-front.pages.dev
      - --port=:11648
    ports:
      - "127.0.0.1:11648:11648"
    env_file:
      - .env
    environment:
      - OTEL_SERVICE_NAME=api
    volumes:
      - type: bind
        source: ${NGA_DATA_DIR?Please set NGA_DATA_DIR to a host directory that contains nga.db}
        target: /data

  fe:
    image: node:22-alpine
    working_dir: /app
    command:
      - sh
      - -c
      - npm install && npm run dev
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - type: bind
        source: ./fe
        target: /app
    restart: unless-stopped
    profiles:
      - fe
